/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CommentUpdateManyWithoutMealsInput } from "./CommentUpdateManyWithoutMealsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsNumber,
  Min,
  Max,
} from "class-validator";
import { Type } from "class-transformer";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { LikeUpdateManyWithoutMealsInput } from "./LikeUpdateManyWithoutMealsInput";
import { PaymentUpdateManyWithoutMealsInput } from "./PaymentUpdateManyWithoutMealsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class MealUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CommentUpdateManyWithoutMealsInput,
  })
  @ValidateNested()
  @Type(() => CommentUpdateManyWithoutMealsInput)
  @IsOptional()
  @Field(() => CommentUpdateManyWithoutMealsInput, {
    nullable: true,
  })
  comments?: CommentUpdateManyWithoutMealsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  ingredients?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => LikeUpdateManyWithoutMealsInput,
  })
  @ValidateNested()
  @Type(() => LikeUpdateManyWithoutMealsInput)
  @IsOptional()
  @Field(() => LikeUpdateManyWithoutMealsInput, {
    nullable: true,
  })
  likes?: LikeUpdateManyWithoutMealsInput;

  @ApiProperty({
    required: false,
    type: () => PaymentUpdateManyWithoutMealsInput,
  })
  @ValidateNested()
  @Type(() => PaymentUpdateManyWithoutMealsInput)
  @IsOptional()
  @Field(() => PaymentUpdateManyWithoutMealsInput, {
    nullable: true,
  })
  payments?: PaymentUpdateManyWithoutMealsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { MealUpdateInput as MealUpdateInput };
